### ISSUE TITLE
Error: listen EADDRINUSE :::8089

### ISSUE THREAD

**Issue by sull** [beakerbrowser/dathttpd#10]
I don't have port 8089 in my .dathttpd.yml (removed metric entry).
I noticed it was hardcoded in lib/metric.js.
Regardless, my server is not showing 8089 being used by any process. 
But if I try to start dathttpd, this is the error I keep getting.

**Comment by taravancil** [comment]
You're right, the metrics server runs by default on port 8089.

Strange that 8089 doesn't appear to be used though. Maybe you've already tried this, but does this still happen if you stop dathttpd and then start it again?

**Comment by pfrazee** [comment]
Try setting it to a different port and see what happens. Not sure what could be going on here.

**Comment by sull** [comment]
I'm setting up a new dedicated server (was just initial test before). I'll post my results.

**Comment by sull** [comment]
Seems to be working properly on new test server. 

Testing with your dat'ified blogs:

[https://paulfrazee.no.center](https://paulfrazee.no.center)
[https://taravancil.no.center](https://taravancil.no.center)

**Comment by pfrazee** [comment]
👍  good deal! closing for now

**Comment by sull** [comment]
This test was using wildcard dns. I noticed the letsencrypt cert did not create unique cert for each test subdomain that I had added. I'll look into letsencrypt current support for wildcard certs. Anything worth discussing on the dathttpd side?

Also, is a .well-known supposed to get created? Not seeing it.

**Comment by pfrazee** [comment]
It didnt create unique certs? That's a sign of a bug, it should definitely support that right now.

The .well-known is served dynamically on the https server.
