### ISSUE TITLE
config file env var

### ISSUE THREAD

**Issue by millette** [beakerbrowser/dathttpd#18]
According to https://github.com/beakerbrowser/dathttpd/blob/master/lib/manager.js the env. variable is ```CONFIG``` and not ```DATHTTPD_CONFIG``` as specified in the readme and in
[index.js on line 18](https://github.com/beakerbrowser/dathttpd/blob/89ceb683a7c5ca2e9eeb6878add050b4ebe997a0/index.js#L18).

**Comment by pfrazee** [comment]
Good catch, thanks for reporting! Any preference on which we use, `DATHTTPD_CONFIG` or `CONFIG` ?

**Comment by millette** [comment]
I would tend toward the more verbose option, but I think I'm the exception. That said, ```CONFIG``` could exist in the environment and skew expectations.

**Comment by pfrazee** [comment]
> That said, CONFIG could already exist in the environment and skew expectations.

Let's use `DATHTTPD_CONFIG` then. Added to my todo list. Thanks agian
