### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by luandro** [beakerbrowser/dathttpd#21]
Creating a Dockerfile would make testing this easy as pie. Got any plans for this? Haven't used Docker that much but I could try to hack one out.

**Comment by pfrazee** [comment]
Feel free, I dont use docker myself but I'd accept a PR

**Comment by luandro** [comment]
I've been trying but Docker hasn't been on my side. If anyone wants to try, [this](https://github.com/luandro/dathttpd/blob/master/Dockerfile) is what I've been trying.

I'll close this, cheers!

**Comment by pfrazee** [comment]
Sorry to hear that. If I ever get a spare moment, I'll give it a shot.
