### ISSUE TITLE
Peering

### ISSUE THREAD

**Issue by taniki** [beakerbrowser/dathttpd#24]
I have a dathttpd installed on a rpi behind a NAT and a dyndns. Everything is working fine except keys are not peering changes when not on the same LAN.

Is there any extra port I should open beside 80 and 443?

I have checked DAT specs but cannot find such info.

**Comment by pfrazee** [comment]
Dat tries 3282 first. If that fails, it'll pick any random unprivileged port.

**Comment by taniki** [comment]
I forwarded that port on my router and it worked.

Thanks!

**Comment by pfrazee** [comment]
Great!
