### ISSUE TITLE
Dat serving only works with HTTPS enabled

### ISSUE THREAD

**Issue by brechtpm** [beakerbrowser/dathttpd#34]
I tried to run a dathttpd configuration with the setting `letsencrypt: false`. When doing this I could access sites through `http://` just fine, but viewing them through `dat://` didn't work. I noticed in two different environments (my public VPS and a local Raspberry Pi), so I'm not sure if this is a bug or a security precaution of some kind.

I'm now running a setup with HTTPS enabled on my VPS, which works as expected.

**Comment by pfrazee** [comment]
The Dats are served without https, but the Dat DNS shortnames won't work. That's because Dat DNS *requires* the `.well-known/dat` file to be served over DNS. See https://github.com/beakerbrowser/beaker/wiki/Authenticated-Dat-URLs-and-HTTPS-to-Dat-Discovery
