### ISSUE TITLE
web_root?

### ISSUE THREAD

**Issue by edwardsharp** [beakerbrowser/dathttpd#39]
the https version of my dat site doesn't seem to use the `web_root` path config from my dat archive. when i use the p2p version it works fine. is there a way to configure this?

**Comment by pfrazee** [comment]
This project is being replaced by https://github.com/beakerbrowser/homebase (which is basically the same as dathttpd but with a rewrite and some new features). Homebase's HTTPS mirror supports `web_root` as you'd expect

**Comment by edwardsharp** [comment]
ohyea; swank! got that working, thank you 😄
