### ISSUE TITLE
Https / LetsEncrypt renewall

### ISSUE THREAD

**Issue by dblodorn** [beakerbrowser/dathttpd#40]
Hi!

Appreciate the extremely streamlined workflow here! But wondering how renewing the generated ssl certificates might be handled in an equally elegant manner.

I usually use certbot, but alongside nginx. I tried installing it along with letsencrypt on my ubuntu servers - but as node is the web server in this case - i get this error: Problem binding to port 80: Could not bind to IPv4 or IPv6.

Has this issue been explored, is there a simple way to renew, I'll look into it further but just wanted to reach out for any existing solutions.

Im running this on a digital ocean ubuntu 16.04 droplet.]

Thanks!

**Comment by pfrazee** [comment]
Hey @dblodorn. First of all, we're replacing dathttpd with https://github.com/beakerbrowser/homebase so at some point you might want to switch over.

Second of all, dathttpd *should* handle cert renewal for you. Is that not happening?

**Comment by dblodorn** [comment]
@pfrazee - Thanks! yeah checking out homebase - looks sick. Will migrate to this.
Yes it seems to have handled the renewalls - i just got a gazillion emails reminding me to renew, but there's probably some way turn those off / or manage frequency.

Psyched to work with self hosted homebase.

**Comment by pfrazee** [comment]
Good deal, lmk if there's anything I can help with

**Comment by pfrazee** [comment]
The memory usage is probably caused by Dat. I can look into tuning it.

**Comment by dblodorn** [comment]
Yeah interesting - these sites of mine are getting like 0 traffic. But i was aiming on publishing a pretty decent amount of unique micro sites up to me server. [https://clickholes.com/](https://clickholes.com/)

screenshot of memory consumption - im using PM2

![screen shot 2018-05-16 at 10 56 01 am](https://user-images.githubusercontent.com/7268786/40134639-e8a56f4a-58f7-11e8-867e-8a9ad9ada435.png)

![screen shot 2018-05-16 at 10 56 16 am](https://user-images.githubusercontent.com/7268786/40134646-ecfed72a-58f7-11e8-9c8a-db5f9f1c571e.png)

**Comment by pfrazee** [comment]
Yeah it might have to do with some caching parameters in Dat.
